ruby-grape/grape-entity

- .rubocop_todo.yml
- CHANGELOG.md
- lib/grape_entity/entity.rb
- spec/grape_entity/entity_spec.rb
In the latest release, the `ArgumentError` resulting when an Entity exposes a non-existing attribute (due to typos, merges, pending database migrations, etc.) gives no context as to which attribute is missing, or even which Entity is to blame (including in the backtrace). In master I notice it now gives a `NoMethodError`. That's arguably an improvement, but it also tends to even further obscure that grape-entity has anything to do with the error.
In short, finding the Entity and attribute responsible for these errors is often difficult and tedious, especially in large codebases. I think a simple change to the exception message will make them much easier to find and fix.  Something along the lines of `NoMethodError: Entities::V1::Session missing attribute 'foo' on …
> Specify which attribute is missing on which Entity

- .rubocop_todo.yml
- CHANGELOG.md
- README.md
- lib/grape_entity/entity.rb
- spec/grape_entity/entity_spec.rb
Add a method to unexpose an attribute. 
**Scenario for use:**
You wish to inherit from a Grape::Entity that has more parameters exposed than the child entity should have exposed, you can simply inherit from the parent and unexpose the parameters that you don't want exposed.
Example:
```ruby
class UserData < Grape::Entity
expose :name
expose :address1
expose :address2
expose :address_state
expose :address_city
expose :email
expose :phone
end
class MailingAddress < UserData
unexpose :email
unexpose :phone
end
```
> Add Unexpose Method

- CHANGELOG.md
- lib/grape_entity/entity.rb
- spec/grape_entity/entity_spec.rb
The valid_exposure check now also accepts Hash objects that have a key matching the attribute's name.
Fix includes `spec` that demonstrates the issue and fails without the changes.
> Fixed exposure of attributes marked as safe when using hash models.

- .rubocop_todo.yml
- CHANGELOG.md
- lib/grape_entity/entity.rb
- spec/grape_entity/entity_spec.rb
Fix now is checking the method arity in the `delegate_attribute` method. With this change the key attribute will be fetched and instead of the `key` method (with arity 1) being invoked.
The fix includes a `spec` that demonstrates the issue and fails without the changes.
> Fix: allow usage of attributes with name 'key' if `Hash` objects are used

- .rubocop_todo.yml
- CHANGELOG.md
- lib/grape_entity/entity.rb
- spec/grape_entity/entity_spec.rb
Currently, exposure is inherited from parent entities to child entities.  So, something like this works:
```
module Foo
module Entities
class GenericEntity < Grape::Entity
expose :id
end
end
end
module Foo
module Entities
class SpecificEntity < GenericEntity
#has :id already exposed
end
end
end
```
However, "root" is not inherited, so the following does not work
```
module Foo
module Entities
class GenericEntity < Grape::Entity
root :data, :object
end
end
end
module Foo
module Entities
class SpecificEntity < GenericEntity
#has no knowledge of parent's root settings
end
end
end
```
This pull request addresses the above, which is useful for those of us who want to have one standard root node name throughout the application and don't want to define it in every entity.
> Root node inheritance

- CHANGELOG.md
- lib/grape_entity/entity.rb
- spec/grape_entity/entity_spec.rb
This is a proposed fix for issue
Subclasses keep the parent's .documentation? #121
Currently each Entity keeps track of its own exposures in a class object instance variable. A new entity class makes a copy of it's parent exposures then goes on and modifies its own exposures (add or remove exposures).
For the moment, I think we can fix the documentation issue by simply removing the call to **superclass.documentation**.
In the future we might have to replace the class object instance variable (which is a simple hash at the moment) with something more elaborate (like a chained filter or something) to handle the child - parent relationship better. Ex. what happens if we add some more exposures to the parent entity after we defined the child entity? I think that the child entity will not …
> Subclass documentation #121

- .rubocop_todo.yml
- CHANGELOG.md
- lib/grape_entity/entity.rb
- spec/grape_entity/entity_spec.rb
This reverts commit 283fc7f562275ddb9760e076545938f8b9c6538d.
> Revert "implement universally unique attributes to silo exposure logic"

- CHANGELOG.md
- lib/grape_entity/entity.rb
- spec/grape_entity/entity_spec.rb
Because less code is better than more.
> Some subtle improvements

- CHANGELOG.md
- lib/grape_entity/entity.rb
- spec/grape_entity/entity_spec.rb
With the addition of the `only` and `except` options, possibilities such as the [partial response](http://bit.ly/1fxWuXJ) design pattern (where the consumer of the API can specifically request only the fields that it desires) become available. A common pattern to request these fields would be via `params`, which will arrive as strings. Currently only an array of symbols (or hash containing symbols) is supported to define the desired fields.
As discussed [here](https://github.com/intridea/grape-entity/pull/114#issuecomment-79122967), it certainly should be the responsibility of another gem to do parameter validation in a partial response scenario, but such a gem would also have to do a [perhaps unnecessary] recursive symbol coercion as well when it could be handled by grape-entity, as …
> Allow for strings in 'only' and 'except' options

- README.md
Refactored namespacing to be more consistent with the one used in the [Example](https://github.com/intridea/grape-entity#example): ``API::Entities::Status``, ``API::Entities::Address``, instead of ``API::Status`` or ``API::Address``, to make it explicit that the presenters should also be GrapeEntities.
> Refactored examples namespacing.

- .rubocop_todo.yml
- CHANGELOG.md
- README.md
- lib/grape_entity/entity.rb
- spec/grape_entity/entity_spec.rb
Make Grape::Entity keep tracking of current being exposed attribute's full path into `options[:attr_path]`.
> tracking attribute path into options[:attr_path]

- lib/grape_entity/exposure/nesting_exposure/nested_exposures.rb
ActiveSupport's `delegate` adds an overhead that we simply don't need.
And it's easy to implement efficient delegation for this specific task.
This patch also adds new methods for delegation: `select`, `all?` and
`each_with_object` that are heavily used internally.
It's a micro-optimization but it's easy to implement so here it is.
> Rewrite array methods delegation to @exposures.

- CHANGELOG.md
- lib/grape_entity/entity.rb
- lib/grape_entity/version.rb
- spec/grape_entity/entity_spec.rb
This one fixes a regression introduced in #147: entity instance methods
were exposed with `NoMethodError`.
Fixes #163. Additional specs are added.
Will be fixed in `0-4` and ported to `master`.
> Fix: entity instance methods exposure (0.4)

- lib/grape_entity/entity.rb
A small typo, but an important one. It definitely confused me for a moment.
> Fix class name in docs

- lib/grape_entity/exposure/base.rb
- spec/grape_entity/entity_spec.rb
This is a regression only in WIP `0.5.0` version: refactored code emits `false`, not `nil` :(
Spec added.
> Fix: exposure safe attributes as nil

- README.md
Just noticed this earlier when I was searching the docs for something. All of the sample code in this example references a `Status` whereas this line was referencing a `User`, which doesn't make sense. I assume this was a typo? :)
> Fixes typo in Entity Organization docs

- CHANGELOG.md
- lib/grape_entity/exposure/represent_exposure.rb
- spec/grape_entity/exposure/represent_exposure_spec.rb
Fixes a tiny bug where calling `.setup` on `RepresentExposure` wouldn't 'reset' `@using_class`. As of this, it was possible that `@using_class` and `@using_class_name` were referencing different classes.
> Fix: reset `@using_class` memoization on `.setup`

- CHANGELOG.md
- UPGRADING.md
- lib/grape_entity/exposure/nesting_exposure/nested_exposures.rb
- spec/grape_entity/exposure/nesting_exposure/nested_exposures_spec.rb
If a given attribute of `delete_if` couldn't be found, `nil` was returned [as described in ruby spec](http://ruby-doc.org/core-2.2.4/Array.html#method-i-reject-21). Although, I expected `@exposures`  to be return, to maintain consistency with the cases when sth. is found.
> Fix: return `self` instead of `nil` if no attribute was deleted

- CHANGELOG.md
- README.md
- lib/grape_entity/entity.rb
- lib/grape_entity/exposure/base.rb
- lib/grape_entity/exposure/nesting_exposure.rb
- lib/grape_entity/exposure/nesting_exposure/output_builder.rb
- spec/grape_entity/entity_spec.rb
This also closes #138
Hi guys. Long time ago I dreamed about merging fields into nested hashes. And that's it. I found it useful and decided to make a PR. 
We can do this:
```ruby
expose :contact_info do
expose :phone
expose :address, merge: true, using: API::Entities::Address
end
```
this:
```ruby
expose :something_useful, merge: true
```
And even this:
```ruby
expose :profiles do
expose :users, merge: true, using: API::Entities::User
expose :admins, merge: true, using: API::Entities::Admin
end
```
It would be awesome if you take a look at this. Thanks!
> Add option :merge to expose. Allow to merge fields into nested hashes and into the root

- .travis.yml
- CHANGELOG.md
- Gemfile
- lib/grape_entity/entity.rb
- spec/grape_entity/entity_spec.rb
- spec/spec_helper.rb
This patch prevents Entity from delegating attributes
to Kernel methods. This is accomplished by testing the
methods the Entity class responds to for ownership
by the Entity class itself.
Fixes #215.
> Do not delegate to Kernel methods.

- CHANGELOG.md
- lib/grape_entity/options.rb
- spec/grape_entity/entity_spec.rb
We use `fetch` often to get options (raising an error if an option doesn't exist) as well as to provide a alternative value if an option is not provided.
> Add fetch method to fetch from opts_hash

- CHANGELOG.md
- Gemfile
- grape-entity.gemspec
- lib/grape_entity/exposure/nesting_exposure/output_builder.rb
- spec/grape_entity/entity_spec.rb
#213 
Hi everyone :suspect: 
The problem that we've changed the `Hash` output to the `OutputBuilder` one (see #204) . Even though an `OutputBuilder` instance delegates everything to its `output` object (which is a `Hash`) - it  returns `false` when we do this: `.is_a?(Hash)` on a `OutputBuilder` instance. `is_a?` method is not delegated. And grape errors formatters expect to get a `Hash` instance from `Entity` after representation, not `OutputBuilder` one.
I checked grape master branch and my grape-entity branch tests. Everything should be fine.
> Let the OutputBuilder be the Hash as well

- CHANGELOG.md
- lib/grape_entity/exposure/nesting_exposure/output_builder.rb
- spec/grape_entity/entity_spec.rb
Currently, if something is exposed with `merge: true` and the value ends up being `nil`, it raises an unhandled exception. This changes that behavior to add nothing to the output and throw no exception
> Fix nil values causing errors when merge option passed

- .travis.yml
- CHANGELOG.md
- Gemfile
- Rakefile
- grape-entity.gemspec
- lib/grape_entity/condition/base.rb
- lib/grape_entity/entity.rb
- lib/grape_entity/exposure/base.rb
- lib/grape_entity/exposure/nesting_exposure.rb
- lib/grape_entity/exposure/nesting_exposure/output_builder.rb
- lib/grape_entity/options.rb
- spec/grape_entity/entity_spec.rb
… align dependencies with other grape gems
~~https://github.com/ruby-grape/grape-entity/pull/209 should be mörged before~~
> moves dev dependencies into gemspec

- .rubocop_todo.yml
- CHANGELOG.md
- lib/grape_entity/entity.rb
- lib/grape_entity/exposure/nesting_exposure/nested_exposures.rb
New versions of RSpec have warnings turned on by default:
config.warnings = true
I believe these warnings are helpful in general to write better code. However, Grape Entity is very noisy. I get more than 10 lines of warnings for one single test where Grape Entity is involved.
I hope you agree. Some of my changes could also be solved differently for sure. I am happy to discuss and change those cases. I also turned warnings on in the test suite.
> Avoid noise when code runs with Ruby warnings

- CHANGELOG.md
- lib/grape_entity/entity.rb
- lib/grape_entity/exposure/base.rb
- lib/grape_entity/exposure/nesting_exposure.rb
- lib/grape_entity/exposure/nesting_exposure/nested_exposures.rb
- lib/grape_entity/exposure/nesting_exposure/output_builder.rb
- lib/grape_entity/exposure/represent_exposure.rb
- spec/grape_entity/entity_spec.rb
- spec/grape_entity/exposure/nesting_exposure/nested_exposures_spec.rb
- spec/grape_entity/exposure_spec.rb
This adds the ability to specify keys dynamically in the expose as: using a proc. This uses the syntax as preferred by @dblock in #172 
```ruby
object = OpenStruct(awesomness: 'awesome_key', awesome: 'not-my-key' )
class MyEntity < Grape::Entity
expose :awesome, as: -> { object.awesomness }
end
=> { 'awesome_key': 'not-my-key' }
```
I've included #264 as it made seeing the wood for the trees easier when testing.
> Allow dynamic keys via as: proc

- grape-entity.gemspec
Ruby 2.2 is still alive and fixing minimal version to 2.2.6 would cause many issues for applications out there that are still on older version of series 2.2
> Relax minimal Ruby version requirement

- Gemfile
- grape-entity.gemspec
ref: https://github.com/bbatsov/rubocop/commit/dd0d60c0a87bdb6233cdeca14a13505b10f2bfae
https://github.com/ruby-grape/grape-entity/pull/277 failed as https://travis-ci.org/ruby-grape/grape-entity/jobs/295161671 from rubocop 0.48~0.51 changes.
> Freeze rubocop version for stable CI

- CHANGELOG.md
- lib/grape_entity/entity.rb
- spec/grape_entity/entity_spec.rb
I've faced this problem when Rubocop suggested to fix `Style/SymbolProc` problem in the following code:
```ruby
expose :something do |object|
object.any_method
end
```
After the fix the following code started to throw wrong argument number exception, because options are always passed to the block:
```ruby
expose :something, &:any_method
```
I'm aware of the `as:` option which solves the case above, but probably this enhancement will help avoid confusion with Rubocop users.
> Fix wrong argument exception when &:block passed to the expose method

- CHANGELOG.md
- lib/grape_entity/condition.rb
- lib/grape_entity/condition/block_condition.rb
- lib/grape_entity/delegator.rb
- lib/grape_entity/entity.rb
- lib/grape_entity/exposure.rb
- lib/grape_entity/exposure/nesting_exposure.rb
- lib/grape_entity/options.rb
Made an attempt to make code more short and readable (e.g. unified interfaces, removed repetitive code, ruby build-in added delegation etc)
> Refactor and simplify various modules and classes

- .rubocop_todo.yml
- CHANGELOG.md
- lib/grape_entity/entity.rb
- lib/grape_entity/exposure/base.rb
- lib/grape_entity/exposure/nesting_exposure/nested_exposures.rb
- spec/grape_entity/entity_spec.rb
Tried to fix issue #286 by allowing to override exposures in child classes when the exposure is not conditional and not nesting
> Allow replace non-conditional non-nesting exposures in child classes

- .rubocop_todo.yml
- CHANGELOG.md
- README.md
- lib/grape_entity/entity.rb
- lib/grape_entity/exposure.rb
- spec/grape_entity/entity_spec.rb
Addresses #216 and #10 
I read through both of the issues to help guide naming, default behavior etc. 
Some basic high level details
* expose_nil defaults to true
* is implemented as an unless condition
* the option is transformed as part of Exposure.compile_conditions
Currently rubocop is failing because my new tests make the `describe` block too long. I'm not sure how you all typically handle something like this so just let me know what I should do.
```
Running RuboCop...
Inspecting 38 files
...............................C......
Offenses:
spec/grape_entity/entity_spec.rb:6:1: C: Metrics/BlockLength: Block has too many lines. [1625/1496]
describe Grape::Entity do ...
^^^^^^^^^^^^^^^^^^^^^^^^^
38 files inspected, 1 offense detected
RuboCop failed!
```
> Add expose_nil option

- .rubocop_todo.yml
- CHANGELOG.md
- README.md
- lib/grape_entity/entity.rb
- lib/grape_entity/exposure/base.rb
- spec/grape_entity/entity_spec.rb
Per discussion here https://github.com/ruby-grape/grape-entity/issues/296. Please note that I've removed all other conditions, so even conditional or nesting exposure can be overwritten (should I throw an error or something when people configure their exposures in strange ways?)
> Introduce override option for expose

- README.md
The service for one of the build status badges has been closed. This PR removes the badge.
> README: Drop defunct badge for gemnasium service

- .travis.yml
- this keeps CI matrix creation in "rvm" settings
- trust RVM to have updated RubyGems
> CI: Define matrix one way

- README.md
In addition to `object`, the entity options are available to access via this [attr_reader](https://github.com/ruby-grape/grape-entity/blob/master/lib/grape_entity/entity.rb#L47)
Some context - 
We had a PR with logic in it that looked like:
```
class Api
resources ... do
get '...' do
present resource, with: ....Entity, variant: params[:variant]
end
end
end
class ...Entity
expose :html do |_, options|
@variant = options[:variant]
html
end
private
def html
...FetchHtml.call(resource: resource, variant: @variant)`
end
end
```
Instead of:
```
class ...Entity
expose :html
private
def html
...FetchHtml.call(resource: resource, variant: options[:variant])`
end
end
```
The concern with using `options` directly was that it wasn't documented.
I didn't update the CHANGELOG since this is just a …
> Add options usage notes to README.

- .rubocop.yml
- CHANGELOG.md
- lib/grape_entity/delegator/fetchable_object.rb
- lib/grape_entity/delegator/hash_object.rb
- lib/grape_entity/delegator/openstruct_object.rb
- lib/grape_entity/delegator/plain_object.rb
- lib/grape_entity/entity.rb
- spec/grape_entity/hash_spec.rb
Before this change the only way I could find to access a hash with string keys
was to either convert it to a symbol hash or define methods in the entity.
This should at least allow the entire hash to be accessed with string keys yet default to existing behavior (symbol keys).
If anyone has suggestions for how to improve this I'm all ears. This was just the quickest least intrusive thing I could think of at the time.
> Support hashes with string keys

- .rubocop.yml
- lib/grape_entity/entity.rb
Hi!
This PR contains the following fixes for RuboCop:
- Follow up RuboCop v0.77 
- The `Layout/IndentFirstHashElement` cop has renamed to `Layout/FirstHashElementIndentation` (https://github.com/rubocop-hq/rubocop/pull/7468).
- Remove the unnecessary disabling of `Style/IfUnlessModifier` cop to resolve the failed CI:
- https://travis-ci.org/ruby-grape/grape-entity/jobs/606754710
> Fix RuboCop issues

- grape-entity.gemspec
The RubyGems property rubyforge_project is removed without a replacement.
> Gemspec: Drop EOL'd property rubyforge_project

- CHANGELOG.md
On every new PR Danger changelog check is complaining because of missing dash:
---
I'm not sure if line in question should be both in fixes and features. But it got to have dash before author's name.
> Adds missing dash

- CHANGELOG.md
- lib/grape_entity/exposure.rb
- spec/grape_entity/entity_spec.rb
Greetings,
I've been trying to implement a conditional exposure at one of the entities in my project.
Noticed that in the current implementation, this code 
```ruby
expose :personal_details, expose_nil: false do |address, options|
if options[:one_option].present?
Public::Entities::PersonalDetail.represent address.personal_details
elsif options[another_option].present?
Public::Entities::PersonalDetailShort.represent address.personal_details
else
nil # explicit for the example
end
end
```
will eventually expose `null` if both conditions are not satisfied.
This PR fixes the specified issue.
> Option expose_nil doesn't work when block is passed

- .travis.yml
- CHANGELOG.md
- Gemfile
Previous attempt to [update matrix](#318) failed because rubocop version is not fixed so `~> 0.65` resolved to version above `0.75`.  I guess it was mistake not to define it as `~> 0.65.0` 
Last version of rubocop passing is `0.74` so fixing that version.
Bumping of rubocop could be addressed in own PR.
> CI: Use 2.5.7,  2.6.5, 2.7.0

- CHANGELOG.md
- lib/grape_entity/delegator/fetchable_object.rb
- lib/grape_entity/delegator/openstruct_object.rb
- lib/grape_entity/delegator/plain_object.rb
- lib/grape_entity/entity.rb
This change reduces hash allocations.
Here is a simplified example what was happening.
```ruby
def do_not_accept_keywords(**)
end
100.times { do_not_accept_keywords(hash: true) }
```
After measuring via memory profiler, we got this:
Total allocated: 69600 bytes (300 objects)
allocated memory by location
-----------------------------------
69600  profile/sample.rb:15
It points to a line where the method gets called. So, every call created a separate hash. It was happening for `Grape::Entity::Delegator::PlainObject`.
If options get extracted, the picture is better.
```ruby
def do_not_accept_keywords(**)
end
opts = { hash: true }
100.times { do_not_accept_keywords(opts) }
```
Allocation:
Total allocated: 46632 bytes (201 objects)
allocated memory by location …
> pass options to delegators when they accept it

- CHANGELOG.md
- lib/grape_entity/entity.rb
Fix warning with keyword arguments:
`/Users/begotten63/.rvm/gems/ruby-2.7.1/gems/grape-entity-0.8.1/lib/grape_entity/entity.rb:540: warning: Using the last argument as keyword parameters is deprecated; maybe ** should be added to the call`
`/Users/begotten63/.rvm/gems/ruby-2.7.1/gems/grape-entity-0.8.1/lib/grape_entity/delegator/hash_object.rb:7: warning: The called method 'delegate' is defined here`
> Fix ruby 2.7 deprecation warning

- .travis.yml
- CHANGELOG.md
- lib/grape_entity/entity.rb
- lib/grape_entity/exposure/nesting_exposure/output_builder.rb
- removes 2.4.10 tests
- move 2.5.8 to allowed failures -> not official supported anymore
> Adds ruby 3.0.0 to travis.

- lib/grape_entity/entity.rb
I found a comment that seems to be a typo, so I suggest a fix.
> Fix typo in comments in lib/grape_entity/entity.rb

- CHANGELOG.md
- README.md
- lib/grape_entity/entity.rb
- lib/grape_entity/exposure/base.rb
- spec/grape_entity/entity_spec.rb
I noticed there is no direct way of defining default value for `expose` when a field is returning `nil`. Of course there is a way to do it via a block but would be a nice option to have it like this:
`expose :x, default: 0`
I also saw there is an issue opened https://github.com/ruby-grape/grape-entity/issues/327 asking for the feature so I made the pr maybe it will be useful for other folks.
> Add default value option

- .rubocop.yml
- CHANGELOG.md
- lib/grape_entity/condition/base.rb
- lib/grape_entity/entity.rb
- lib/grape_entity/exposure.rb
- lib/grape_entity/exposure/base.rb
- spec/grape_entity/entity_spec.rb
As @zverok deduced when [opening the issue](https://github.com/ruby-grape/grape-entity/issues/378#issue-1853710374), the wrong options are getting used when pairing `expose_nil: false` with a block.
Fixes #378
> Pass the right options when determining whether to expose an attribute using a block

- .rspec
- grape-entity.gemspec
- lib/grape_entity/entity.rb
- lib/grape_entity/json.rb
- spec/grape_entity/entity_spec.rb
- spec/grape_entity/exposure/nesting_exposure/nested_exposures_spec.rb
- spec/grape_entity/exposure/represent_exposure_spec.rb
- spec/grape_entity/exposure_spec.rb
- spec/grape_entity/hash_spec.rb
- spec/grape_entity/json_spec.rb
- spec/grape_entity/options_spec.rb
This PR adds a `Grape::Entity::Json` class that will use `multijson` if already loaded instead of the default `json`.
A spec has been added to make sure `to_json` still works and moved `require 'spec_helper'` in `.rspec` file
> Drop `multijson` dependency

- lib/grape_entity/entity.rb
- spec/grape_entity/entity_spec.rb
Ruby 3’s stricter Proc arity rules could slip unwanted arguments into &:method_name exposures, causing confusing errors. This change detects pure symbol-to-proc wrappers up front, looks up the actual method’s arity on the entity object, and raises an error if it’s not zero. Regular blocks still use their own arity to decide whether to pass options. In practice, this makes it impossible to accidentally expose a one- or two-argument method with &:foo, ensuring only truly zero-argument methods are used in that shorthand.
Possible sollution #376
> Block arity detection
